### ISSUE TITLE
@SuperCommand example in doc/wiki?

### ISSUE THREAD

**Issue by DrDaleks** [jbock-java/jbock#32]
Not really clear how `@Command` and `@SuperCommand` can/should be used in combination. Would it be possible to get an illustrated example (in the wiki or in the examples folder)? I'd say "git" is a good example of command to illustrate the expected behaviour.

**Comment by h908714124** [comment]
Thanks for pointing this out. I've added a new method `CommandModel.toBuilder()` in 5.15.

**Comment by h908714124** [comment]
Good point, the documentation for SuperCommand needs some work.
It is not possible to combine Command and SuperCommand.
Here's a minimal example:
https://github.com/jbock-java/jbock/blob/dd6a4aa11f34a709b3484226183036ce9c253d33/examples/src/main/java/net/jbock/examples/GitCommand.java
https://github.com/jbock-java/jbock/blob/dd6a4aa11f34a709b3484226183036ce9c253d33/examples/src/test/java/net/jbock/examples/GitCommandTest.java

**Comment by h908714124** [comment]
Hello again, just letting you know:
There was a breaking change in `5.16`.
The class `SuperResult` was removed,
instead the `@SuperCommand` must have a `@VarargsParameter` of type `List<String>`.
See updated wiki page.
